// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: You need to replace these placeholder values with your actual Firebase project configuration.
/// 
/// To set up Firebase properly:
/// 1. Go to https://console.firebase.google.com/
/// 2. Create a new project or select existing one
/// 3. Enable Authentication in the Firebase console
/// 4. Enable Email/Password authentication
/// 5. Enable Email verification
/// 6. Add a web app to your project
/// 7. Copy the configuration values from the Firebase console
/// 8. Replace the placeholder values below
/// 
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Your actual Firebase configuration values
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7znqd02xZn-LHNPtP90pHkHKiE9T9PxY',
    appId: '1:625868860063:web:20ce71c59bc91292fdd0aa',
    messagingSenderId: '625868860063',
    projectId: 'dimhans-app',
    authDomain: 'dimhans-app.firebaseapp.com',
    storageBucket: 'dimhans-app.appspot.com',
    measurementId: 'G-XFJ153QHN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7znqd02xZn-LHNPtP90pHkHKiE9T9PxY',
    appId: '1:625868860063:web:20ce71c59bc91292fdd0aa',
    messagingSenderId: '625868860063',
    projectId: 'dimhans-app',
    storageBucket: 'dimhans-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7znqd02xZn-LHNPtP90pHkHKiE9T9PxY',
    appId: '1:625868860063:web:20ce71c59bc91292fdd0aa',
    messagingSenderId: '625868860063',
    projectId: 'dimhans-app',
    storageBucket: 'dimhans-app.appspot.com',
    iosClientId: 'YOUR-IOS-CLIENT-ID-HERE',
    iosBundleId: 'com.example.dimhansApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7znqd02xZn-LHNPtP90pHkHKiE9T9PxY',
    appId: '1:625868860063:web:20ce71c59bc91292fdd0aa',
    messagingSenderId: '625868860063',
    projectId: 'dimhans-app',
    storageBucket: 'dimhans-app.appspot.com',
    iosClientId: 'YOUR-IOS-CLIENT-ID-HERE',
    iosBundleId: 'com.example.dimhansApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7znqd02xZn-LHNPtP90pHkHKiE9T9PxY',
    appId: '1:625868860063:web:20ce71c59bc91292fdd0aa',
    messagingSenderId: '625868860063',
    projectId: 'dimhans-app',
    storageBucket: 'dimhans-app.appspot.com',
  );
} 